### ISSUE TITLE
Purpose of this SmartComponent

### ISSUE THREAD

**Issue by DiegoVil** [DenisFR/RSDrawGraphics#1]
Hi there,

this is not an issue. Is a question. What is the user case of this component? Why I should draw in RAPID instead of doing it in RobotStudio?

Anyway thanks for uploading this!

**Comment by DenisFR** [comment]
Hello,
This component is for showing shapes managed in RAPID.
These shapes are used to manage collision detection, as you can found in modGfxShapeData.
MainModule show how you can use it.

**Comment by DiegoVil** [comment]
Thanks!
